### ISSUE TITLE
No response when clicking on "Edit menu..." and "Edit template..."

### ISSUE THREAD

**Issue by jkishner** [scripting/1999-project#1]
When I click on "Edit menu..."

```
[Log] You clicked on document. (chat.js, line 1451) 
[Log] readHttpFileThruProxy: url == http://fargo.io/code/shared/outlinedialog.html, error == error. (utils.js, line 396)
[Log] opInitOutliner: font == Ubuntu, fontSize == 15, lineHeight == 22 (outliner.js, line 652)
[Log] afterOpenCallback: about to expand everything. (chat.js, line 666)
[Error] Failed to load resource: Could not connect to the server. (httpReadUrl, line 0)
```

When I click on 'Edit template..."

```
[Log] You clicked on document. (chat.js, line 1451)
[Log] readHttpFileThruProxy: url == http://fargo.io/code/shared/outlinedialog.html, error == error. (utils.js, line 396)
[Log] opInitOutliner: font == Ubuntu, fontSize == 15, lineHeight == 22 (outliner.js, line 652)
[Log] afterOpenCallback: about to expand everything. (chat.js, line 746) 
[Error] Failed to load resource: Could not connect to the server. (httpReadUrl, line 0)
```

**Comment by scripting** [comment]
I have an idea what might be going wrong here.

Are you doing this somewhere where ports other than 80 might be blocked?

Dave

**Comment by jkishner** [comment]
As per a suggestion in the Google group, I entered the following command in
terminal so that I could run it on 80. I do not know if it blocks other
ports.

```
sudo setcap 'cap_net_bind_service=+ep' /usr/bin/nodejs
```

https://gist.github.com/firstdoit/6389682

**Comment by scripting** [comment]
I asked a different question -- what matters in this case is where YOU are not where your server is.

In any case if you are in a place that has a firewall that blocks non-80 ports, I believe I just removed that problem. Could you try editing the menu and template again and see if the editor opens.

Dave

**Comment by jkishner** [comment]
Oh, I misunderstood. Yes at my day job :1999 is blocked. 

Right now I cannot get the editor to open, but I don't know the last time the app updated. (Would I find this at the end of the forever log?)

**Comment by scripting** [comment]
This fix was not in the server it was in the editor.

I need to write a howto that explains all this stuff. I know it's confusing.

To test to see if it's fixed, do the following:
1. In the browser reload your home page. This will cause the new
   browser-based software to reload. That's where the workaround was added.
2. You might need to do a hard reload to be sure everything gets loaded.
3. Now try to open the Menubar or Template.

Dave

**Comment by jkishner** [comment]
The menubar and template editor now open for me. But after I added a link
to the menu, I do not see any changes. I even republished all pages and see
no change in the menu.

**Comment by scripting** [comment]
Okay let's pause here for a moment. I'm going to close this issue now. 

Report a new one, and remember to say what steps you did, carefully, so I can try to reproduce.

Remember, I have to be able to do that to figure out what's going on.
