### ISSUE TITLE
Dropdown menu on published pages not responding: alertDialog is not defined

### ISSUE THREAD

**Issue by scotthansonde** [scripting/1999-project#10]
I noticed that on published pages, the dropdown menu points "About 1999…" and "Settings…" did not respond. In the console was the following error:

```
Uncaught ReferenceError: alertDialog is not defined
settingsCommandNotImplemented @ code.js:32
onclick @ 0009.html:1
```

I was able to fix this locally by adding this to the <head> in my template:

```
<script src="http://fargo.io/code/node/shared/alertdialog.js"></script>
```

**Comment by scripting** [comment]
Thanks for the report Scott. 

It was an easy fix. ;-)
