### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by JPhilpin** [scripting/1999-project#11]
All nicely working - so I thought this morning that I would use IFTTT to take what I post to 1999 - and route it to my twitter account ... it didn't work 

Screen shot shows result - although when i validated it through the IFTTT link to W3 - it said the feed was valid. Maybe it is their issue - not 1999 - just flagging.

![trigger](https://cloud.githubusercontent.com/assets/18621554/14754084/04d03c52-088e-11e6-9c3d-3487112fa8fc.jpg)

**Comment by scripting** [comment]
That's the home page of the site, not the feed.

**Comment by JPhilpin** [comment]
so changed to http://my.1999.io/users/jgphilpin/rss.xml - IFTTT accepted - so will now work to test and tune .... note to self - 'stop being a boy and read ALL instructions first !!'

Thank you sir.
