### ISSUE TITLE
Trailing Backslash

### ISSUE THREAD

**Issue by JPhilpin** [scripting/1999-project#12]
I have noticed consistently that (say)

http://my.1999.io/users/WaltLudwick/ renders as you would expect

Whereas

http://my.1999.io/users/WaltLudwick creates an error message

{
    "code": "EISDIR",
    "errno": "EISDIR",
    "syscall": "read"
}

**Comment by scripting** [comment]
This problem should be fixed in the latest server release v0.94i.

For example -- 

http://my.1999.io/users/jgphilpin

Should now redirect to your home page.
