### ISSUE TITLE
Unable to edit post after inserting HTML

### ISSUE THREAD

**Issue by stoppableforce** [scripting/1999-project#14]
This morning, I tried the "Insert HTML" function for the first time and found that it made my editor completely unresponsive.

Steps to reproduce. Mostly these are as per [Dave's demo](https://www.youtube.com/watch?v=sbqv9SwlFrw&feature=youtu.be).
1. Write a new blog post, and hit "Post." (I have "Publish automatically" turned off; unsure if this is relevant.)
2. Click in the post's body to edit it.
3. From the post dropdown menu, choose "Insert HTML."
4. Paste in the raw HTML and click OK.

From this point on, I am unable to edit the post from the editor, even if I save the update (thus ending the edit) and start a new edit. I _was_ able to edit the story from the story page.

**Comment by scripting** [comment]
It probably matters what HTML you inserted. ;-)

Please think this through -- you have to imagine we've done those steps before. That's how you use the feature.

**Comment by stoppableforce** [comment]
It definitely wasn't anything unusual - it was the same thing you did in the demo video, embedding a youtube video into a post.

To be more precise, it was this:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/7KgT13asGmU" frameborder="0" allowfullscreen></iframe>`

**Comment by scripting** [comment]
Repeatable? (I could be replaced by a robot.)

**Comment by stoppableforce** [comment]
I somehow doubt a robot could have invented all this cool stuff. ;)

I am unable to repeat it now (on a new post), and can now in fact edit the previous post that was causing the problem. Just a weird editor hiccup?

**Comment by scripting** [comment]
Heh. I meant a robot could ask these questions.

I think you have to chalk it up to "shit happens" and "life is good."

Thanks for the good humor. ;-)
