### ISSUE TITLE
Insert HTML works only if post is being edited

### ISSUE THREAD

**Issue by scotthansonde** [scripting/1999-project#15]
On the editor page, if I haven't yet clicked on any stories to edit, the "Insert HTML" menu point under the triangle is active and opens the dialog. But when I enter HTML and click OK, nothing happens.

It works as expected when I first click on the story to activate the edit box, then click the triangle to open the "Insert HTML" menu point.

What would I expect to happen? Maybe that the "Insert HTML" menu point would be greyed out if I am not yet editing the post.

**Comment by scripting** [comment]
I understand what's happening and why it doesn't work. I think that graying out the command is a good idea. Thanks.

**Comment by scripting** [comment]
This is fixed in v0.88u. Didn't need to make the menu item gray, I was able to make the command work even if you aren't editing.
