### ISSUE TITLE
Posts with no title missing in RSS 

### ISSUE THREAD

**Issue by kenbooth** [scripting/1999-project#19]
Posts with no title are not appearing in my RSS feed
##### Steps to reproduce
1. Type a new post
2. Save without adding a title
3. Check RSS feed and see item is missing

Steps to get the post into feed
1. Edit original post
2. Set title and save
3. Check RSS feed and see that item is now present
4. If I edit the post again and remove the title the post remains in the feed
##### What you expected to happen

I expected any post without a title to appear in my RSS feed.
##### Other data

1999.io version v.0.89c
Chrome version 50.0.2661.86
OS X 10.11.4
I could not find anyone else using my.1999.io who had title-less posts, but I did see what appeared to be self-hosted 1999 blogs where the title-less posts were appearing in the RSS feed.

**Comment by scripting** [comment]
It's not a bug. If you want items without titles to show up in the feed, then turn off Instant Articles support.

To do so, choose Settings from the system menu, click on the Feed tab, and uncheck the Instant Articles tab.

![image](https://cloud.githubusercontent.com/assets/1686843/14999461/7c979060-1157-11e6-88e6-e600ac382d59.png)
