### ISSUE TITLE
Template Editor Plugin, Error 500 if template.html does not yet exist

### ISSUE THREAD

**Issue by scotthansonde** [scripting/1999-project#22]
On my.1999.io, running the Template Editor brings up an empty edit box if you have never before saved a template. Console shows Error 500 (Internal Server Error).

I then went back to the 1999.io editor, made a minor change to the template in the outline editor and saved it. Then the Template Editor Plugin worked as expected. 

Console output:

```
startup
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
twGetFile: error == {
    "readyState": 4,
    "responseText": "{\n    \"errno\": 34,\n    \"code\": \"NoSuchKey\",\n    \"path\": \"publicFiles/users/papascott/misc/template.html\"\n}",
    "status": 500,
    "statusText": "Internal Server Error"
}
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
twGetFile: error == {
    "readyState": 4,
    "responseText": "{\n    \"errno\": 34,\n    \"code\": \"NoSuchKey\",\n    \"path\": \"publicFiles/users/papascott/misc/template.opml\"\n}",
    "status": 500,
    "statusText": "Internal Server Error"
}
```

![template editor 2016-05-17 09-53-53](https://cloud.githubusercontent.com/assets/8681117/15315048/b0555b30-1c15-11e6-8a15-07d9eb72ff87.png)

Versions: Server 0.94q, Editor 0.89j

**Comment by scotthansonde** [comment]
Now looking at the plugin, I see the feature isn't ready yet 😄 

https://github.com/scripting/1999-project/blob/7144aafe0c7780806a71c1679cd23ba001adee9d/code/templateedit.html#L42-L44

**Comment by scripting** [comment]
It's a good bug report. Keep looking for other problems. They're probably there.

The to-do list on this project was huge. 

And thanks for your help as always! ;-)

**Comment by scripting** [comment]
This bug should now be fixed. Please confirm that you are now able to use the template editor plugin even if you have never edited the template outline. Also you might want to review the source, since you did last time, to make sure it now makes sense. ;-)

Also there's been a change in the URL of the Template Editor app. It's now at this location.

http://1999.io/editors/templateedit.html

I'll also post a note about this on the 1999-server list.

**Comment by scotthansonde** [comment]
OK, it seems to work. On a fresh test account on my.1999.io I was able to open the plugin and have the default template loaded into its editor. And the code makes sense to me, too (if you can't find a html or a opml template for the user, try to load the default template). :-)

I'll keep trying out the plugin in my local installation and let you know if I notice anything strange.
