### ISSUE TITLE
Source Reader (e.g. http://scripting.com/listings/storage.html) unable to get file from Dropbox

### ISSUE THREAD

**Issue by scotthansonde** [scripting/1999-project#23]
Trying to read the structured listing of storage.js (or any other source file I tried) returns an empty textarea and a 404 error in the console.

```
startup
utils.js:557 hitCounter: counter ping accepted by server, group == scripting, page url == http://scripting.com/listings/storage.html
https://dl.dropboxusercontent.com/u/36518280/misc/nodeEditor/fargo.io-code-storage/storage.opml Failed to load resource: the server responded with a status of 404 ()
utils.js:376 readHttpFile: url == https://dl.dropboxusercontent.com/u/36518280/misc/nodeEditor/fargo.io-code-storage/storage.opml, error == {
    "readyState": 4,
    "responseText": "<!DOCTYPE html>\n<html>\n<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n<title>Dropbox - 404</title>\n<link href=\"//www.dropbox.com/static/css/error.css\" rel=\"stylesheet\" type=\"text/css\"/>\n<link rel=\"shortcut icon\" href=\"//www.dropbox.com/static/images/favicon.ico\"/>\n\n</head>\n<body>\n<div class=\"figure\">\n<img src=\"//www.dropbox.com/static/images/psychobox.png\" alt=\"Error: 404\"/>\n</div>\n<div id=\"errorbox\">\n<h1>Error (404)</h1>We can't find the page you're looking for. Check out our <a href=\"https://www.dropbox.com/help\">Help Center</a> and <a href=\"https://forums.dropbox.com\">forums</a> for help, or head back to <a href=\"https://www.dropbox.com/home\">home</a>.\n</div>\n\n</body>\n</html>\n",
    "status": 404,
    "statusText": "error"
}
scripts.js:42 Uncaught TypeError: Cannot read property 'length' of undefined
```

Workaround: copy storage.opml to your Fargo directory and read it with Fargo (you have to remove the "encoding" attribute from the first line with a text editor first, though). :-)

**Comment by scripting** [comment]
Thanks for the report. This was the result of the disk failure I had last week. 

Here are the newly updated files.

http://scripting.com/listings/storage.html

http://scripting.com/listings/pagepark.html

http://scripting.com/listings/noderunner.html

http://scripting.com/listings/rsstoslack.html

http://scripting.com/listings/rivertotweets.html

http://scripting.com/listings/river4.html

http://scripting.com/listings/mywordeditor.html

http://scripting.com/listings/nodestorageapi.html

http://scripting.com/listings/urlshortener.html
