### ISSUE TITLE
Deleted Posts Appear As Ghosts in The Stream

### ISSUE THREAD

**Issue by JPhilpin** [scripting/1999-project#24]
##### Steps to reproduce

1.Go to [http://my.1999.io/users/jgphilpin/2016/05/19/0131.html](Post is called)
1. Click on 'go left button' to see previous post (Post is called Noel Coward)
2. Click on 'go left button' to see previous post (Post is called The Crazy Ones)
3. Click on 'go left button' to see previous post (Post is called Imagine Images)
4. Click on 'go RIGHT button' to see next post (Post is called The Crazy Ones)
5. note that THIS entry is empty of image (although an image does momentarily appear)
6. Click on 'go RIGHT button' to see next post (Post is called The Crazy Ones)
7. note that THIS entry now contains the image
8. Click on 'go RIGHT button' to see next post (Post is called Noel Coward)
##### What you expected to happen

In step 5 - where you see the empty Crazy Ones - this doesn’t appear clicking one way - it does when you click the other way - I would not expect to see it - since it does not exist
##### Other data

That said - it did once. I was experimenting with embedding images - and ended up with two of The Crazy ones - so I simply deleted one of the posts

Safari Browser - 9.1.1 - but I tried with Chrome and got the same result
OSX - 10.11.5

**Comment by scripting** [comment]
This should be fixed in v0.89k.

**Comment by JPhilpin** [comment]
In the 1999 App - I am using v0.89k - though curiously when the mouse rolls over the version number it changes to v0.94q (see attached image)

I have attached 2 images .... 1 is what I see when I go to that part of the river in the app - and the offending (deleted) post is indeed not there

2 is what I see as a visitor in any browser - simply going to the URL [http://my.1999.io/users/jgphilpin/2016/05/19/0128.html](http://my.1999.io/users/jgphilpin/2016/05/19/0128.html)

when I click backwards in chronology this is jumped - going from 

[http://my.1999.io/users/jgphilpin/2016/05/19/0129.html](http://my.1999.io/users/jgphilpin/2016/05/19/0129.html)

directly to 

[http://my.1999.io/users/jgphilpin/2016/05/19/0127.html](http://my.1999.io/users/jgphilpin/2016/05/19/0127.html)

when I go forward through the clicks I see 

[http://my.1999.io/users/jgphilpin/2016/05/19/0128.html](http://my.1999.io/users/jgphilpin/2016/05/19/0128.html)

regardless of browser 

![1](https://cloud.githubusercontent.com/assets/18621554/15416855/93a4c7c8-1e04-11e6-96b1-e73f1479a66e.jpg)
![2](https://cloud.githubusercontent.com/assets/18621554/15416858/97bf80a0-1e04-11e6-9f9e-793b01402d8f.jpg)

**Comment by scripting** [comment]
I don't understand this report. Are you sure you're reloading the pages?

Also your initial report was a duplicate. The other reporter, Scott Hanson, tested the new version, as I did of course, and it works for both of us. 

Here's a link to that issue report. If you have further comments please post them there. I'm going to close this version of the issue.

**Comment by JPhilpin** [comment]
**Comments - No Action - Feedback ONLY**

Apologies - I hadn't seen Scott's report. I have just read through it - and I see you wrote that 

> Also, you shouldn't have to republish any pages.

I still had the problem - as described by Scott - running the latest version of the app.

**That said I have this morning 'Re-published' my pages - and the problem has gone.**

WITHOUT republishing it was still there - a ghost page from before the fix ?

So I ran another test this morning - and added and deleted posts - and behavior is correct.

Conclusion - I should have Republished after you did the fix to flush out old pages - going forward it is all in real time.

Thank you.

**Comment by scripting** [comment]
A different conclusion -- when the program didn't do what you expected look in the console to see if there were any error messages. Otherwise I know what's in the code, and believe strongly that your conclusion here is incorrect. Not saying there couldn't be errors, but I don't have any info from you on error messages.
