### ISSUE TITLE
emoji shortcodes render on single pages but not home page

### ISSUE THREAD

**Issue by jkishner** [scripting/1999-project#3]
http://1999.jeffreykishner.com/users/kishner/

![screen shot 2016-04-07 at 10 56 15 am](https://cloud.githubusercontent.com/assets/1745919/14365003/6fa31d26-fcd9-11e5-91f4-143b6a473859.png)

http://1999.jeffreykishner.com/users/kishner/2016/04/07/0015.html

![screen shot 2016-04-07 at 10 55 33 am](https://cloud.githubusercontent.com/assets/1745919/14365002/6f83162a-fcd9-11e5-9952-6caa659ce54a.png)

**Comment by scripting** [comment]
I believe I fixed this one. Reload the web app and make a change to one of your posts to cause the home page to rebuild.

**Comment by jkishner** [comment]
it's working now
