### ISSUE TITLE
Cannot add a page to the wiki

### ISSUE THREAD

**Issue by andysylvester** [scripting/1999-project#36]
##### Description of the problem

I went to the 1999-project wiki to add a page, but I did not see the new page button as can be seen at https://github.com/scripting/river5/wiki.
##### Steps to reproduce
1. Went to https://github.com/scripting/1999-project/wiki, did not see "New Page" button.
2. Confirmed that I was logged into my Github account
3. Went to https://github.com/scripting/river5/wiki, saw "New Page" button.
##### What you expected to happen

I expected to see a "New Page" button at https://github.com/scripting/1999-project/wiki
##### Other data

No other data, all other information is given above

**Comment by RickCogley** [comment]
I found the same thing, and you can't clone it and do a pull request, either. Apparently repository contributors automatically get write permissions, and, the repository owner can grant individual users edit permissions. 

See: https://help.github.com/articles/changing-access-permissions-for-wikis/

I'd like edit permission on the wiki, so I can make a page about my setup, which I think others may find useful.

**Comment by scripting** [comment]
I started that repo as a place to put docs and sample code I create.

1999 is a blogging system, so there are lots of places you can put stuff you write.

**Comment by RickCogley** [comment]
Ah, I was responding to what you wrote on the top page of the wiki: "If you have docs for running a 1999 server, this is the place to put them." Anyway, ok, will do.
