### ISSUE TITLE
Files in the OPML directory of nodeServer appear to be invalid XML

### ISSUE THREAD

**Issue by scotthansonde** [scripting/1999-project#37]
##### Description of the problem

Files in the OPML directory of nodeServer (https://github.com/scripting/nodeStorage/tree/master/opml) appear to be invalid XML
##### Steps to reproduce
1. Open Little Outliner 2 in Chrome on OSX
2. Drag readme.opml into an open outline
##### What you expected to happen

I expected to be able to view the contents of readme.opml in LO2.
Instead nothing appears and the console gives the error: Uncaught Error: Invalid XML: <?xml encoding="ISO-8859-1" version="1.0"?>
##### Other data

If I change the first line of the file to '<?xml version="1.0"?>', I am able to view the file as expected.

This issue has a very low priority, since it only affects the readability of the documentation and is easy to work around.

[readme.opml.zip](https://github.com/scripting/1999-project/files/467488/readme.opml.zip)

**Comment by scripting** [comment]
I've seen this before.

**Comment by scripting** [comment]
Where did the readme.opml come from?

This is not a nodeStorage problem btw -- that's why I ask.

nodeStorage doesn't know anything about OPML, it's just doing the storage.

**Comment by scripting** [comment]
Never mind. It seems the file came from the OPML folder of the nodeStorage
project, yes?

That means the problem is with the OPML Editor which is what I use to edit
the OPML files.

**Comment by scotthansonde** [comment]
I think we're finally on the same wavelength. :-)

**Comment by scripting** [comment]
There's a new release.

**Comment by scotthansonde** [comment]
Cool, I can now read readme.opml without changing the first line first.

The other opml files in that directory still have the same problem with the XML declaration (the version number must appear before the encoding declaration, now I know that), so I won't mark as closed quite yet. But no rush! :-)
