### ISSUE TITLE
Broken setup.md link: 1999.bullmancuso.io’s server DNS address could not be found.

### ISSUE THREAD

**Issue by jwithington** [scripting/1999-project#39]
##### Description of the problem

This step is in the setup.md doc:

>The website URL will be the value for myDomain specified in your config.json file, as an HTTP url. From the example, it would be http://1999.bullmancuso.io:1999/

That link, as well as http://1999.bullmancuso.io/ and http://bullmancuso.io/ are getting `bullmancuso.io’s server DNS address could not be found`. 

##### Steps to reproduce

Try accessing any of those http://bullmancuso.io/ links

##### Other data 

I confirmed that it's down over here: http://www.isitdownrightnow.com/bullmancuso.io.html

Using macOS 10.12.2 and Chrome.

**Comment by scripting** [comment]
It's not meant to be a real domain.

**Comment by jwithington** [comment]
Whoops. Cheers! 🍻
