### ISSUE TITLE
top of 1st post obscured on home page on mobile

### ISSUE THREAD

**Issue by jkishner** [scripting/1999-project#4]
The following is on an iPhone 6s plus in Safari

screenshot of single story:

https://dl.dropboxusercontent.com/s/tuphdtjjaxczyct/2016-04-11-1234pm.jpg?dl=0
[source](http://1999.jeffreykishner.com/users/kishner/2016/04/11/0018.html)

screenshot of home page

https://dl.dropboxusercontent.com/s/xs2dggi1nhv9lbg/2016-04-11-1233pm.jpg?dl=0
[source](http://1999.jeffreykishner.com/users/kishner/)

**Comment by scripting** [comment]
Thanks for the report. 

There needed to be a style for .divBlogPostList, which I added to styles.css.

Should be fixed now.
