### ISSUE TITLE
changes to template not showing on live site

### ISSUE THREAD

**Issue by jkishner** [scripting/1999-project#5]
Last week I added google analytics code to the head, and it successfully showed up in my source code on the live site. Today I added some text to the footer, and although I see it in preview, it's not showing on the live site, and my Google analytics script is gone too. I'm not sure what else I should report.

v. 88g

**Comment by scripting** [comment]
There have been lots of problems with templates and menus, and last night I rewrote the code to make it, theoretically, much more reliable.

One general tip is that for any changes in the template you have to rebuild your pages.

**Comment by jkishner** [comment]
ok, I republished all pages and am now seeing my template updates.
