### ISSUE TITLE
story doesn't reflect updates when I change the title

### ISSUE THREAD

**Issue by jkishner** [scripting/1999-project#8]
If I set the title and later change it, the change to the title is not reflected on the story page. I have to re-publish all pages to make it happen.

**Comment by scripting** [comment]
I need steps-to-reproduce to have any hope of helping here.

I do this all the time without any trouble.

**Comment by jkishner** [comment]
For example, for
http://1999.jeffreykishner.com/users/kishner/2016/04/05/0013.html I just
changed "$" in the title to "Money"

I am still seeing $ in the title. I have refreshed the page. Nothing is
happening.

**Comment by scripting** [comment]
1. I'm not doubting that something bad is happening.
2. But without steps-to-reproduce, there's nothing I can do.

**Comment by scripting** [comment]
Here's a quick video demo.

https://www.youtube.com/watch?v=sg09VQorLSk&feature=youtu.be

**Comment by jkishner** [comment]
I watched the video. To narrow down my issue: if I do what you did (edit
title on the editor home page), my changes are reflected on the story. If I
attempt to change the title on the _story_ page, the change does not
update, even when I refresh.

**Comment by scripting** [comment]
That helps narrow things down, a bit.

However, when I do that here, it works.

So there must be something else going wrong.

Do you see any error messages in the console or on the server?

**Comment by scripting** [comment]
BTW, I've had other reports on problems with using the in-page editor.

I think a lot of things broke in the last corner-turn that I still need to sweep up.

Luckily right now there's a workaround -- do your editing in the main editor. 

I will report any fixes I make in the in-page editing environment of course. ;-)

**Comment by scripting** [comment]
Question -- is it only the title, or does it not work if you modify the text of the post?

**Comment by jkishner** [comment]
I can successfully modify the text of the post while in the story (as well
as from the home page).

**Comment by scripting** [comment]
Are there any error messages in the JS console? 

If so -- a screen shot please.

**Comment by jkishner** [comment]
This is what I get when I try to change the title on the story page.

![screen shot 2016-04-13 at 4 27 43 pm](https://cloud.githubusercontent.com/assets/1745919/14508273/b1d80340-0194-11e6-98d0-a91c7ce45176.png)

**Comment by scripting** [comment]
This is why I asked for a screen shot. I am a human being. I'll try to make sense of that...

**Comment by scripting** [comment]
Any chance you're trying to use this on your office computer with non-80 ports blocked?

**Comment by jkishner** [comment]
yes

**Comment by scripting** [comment]
This is not a bug in my software.

**Comment by jkishner** [comment]
I don't understand. If you want this software to have widespread use, wouldn't you need to take into account users who can't work with ports like :1999?

**Comment by scripting** [comment]
I can't solve all problems for all people. And this area is for bug tracking in the software. Ask about it on the list if you want. This not an issue for 1999.io. It's an issue with the Internet.
